services:
  - type: web
    name: sira-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        value: sqlite:///./sira_dev.db
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "120"
      - key: ALLOWED_ORIGINS
        sync: false
      - key: DEBUG
        value: "False"
      - key: APP_VERSION
        value: "2.0.0"
